services:
  web:
    build: ../apps/web
    ports:
      - "3000:3000"
    command: npm run dev
    working_dir: /app
    volumes:
      - ../apps/web:/app
      - /app/node_modules

  api:
    build: ../apps/api
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    volumes:
      - ../apps/api:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://zakaria:secret@db:5432/portfolio

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: zakaria
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: portfolio
    ports:
      - "5433:5432"
